[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction --no-scripts",
    "npm install",
]

[phases.build]
cmds = [
    "composer dump-autoload --optimize",
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan storage:link",
]

[start]
cmd = "php artisan migrate --force && php artisan db:seed --class=ProjectSeeder --force; php -c /app/php.ini artisan serve --host=0.0.0.0 --port=$PORT"
